---
fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: master
      hooks:
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: no-commit-to-branch
            stages: [commit]
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: master
      hooks:
          - id: forbid-binary
            exclude: |
                (?x)^(
                    rsc/.*\.(png|gif|pdf)
                )$
          - id: markdownlint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: master
      hooks:
          - id: yamlfmt
